spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
    baseline-on-migrate: true
